version: '3.8'
services:

  postgres:
    image: postgres:15.2-alpine3.17
    restart: always
    container_name: postgres.db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - backend

  nestjs:
    build: ./backend.nestjs
    restart: always
    container_name: nestjs.back
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - APP_PORT=${APP_PORT}
      - THROTTLER_TTL=${THROTTLER_TTL}
      - THROTTLER_LIMIT=${THROTTLER_LIMIT}
      - DATABASE_URL=${DATABASE_URL}
      - FORTYTWO_CLIENT_ID=${FORTYTWO_CLIENT_ID}
      - FORTYTWO_CLIENT_SECRET=${FORTYTWO_CLIENT_SECRET}
      - FORTYTWO_CALLBACK_URL=${FORTYTWO_CALLBACK_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
    volumes:
      - ./backend.nestjs/src:/app/src
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - backend

  redis:
    image: redis:7.0.8-alpine3.17
    restart: always
    container_name: redis.cache
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:
