version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: always
    container_name: postgres.db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

  nestjs:
    build: ./backend.nestjs
    restart: always
    container_name: nestjs.back
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - APP_PORT=${APP_PORT}
      - THROTTLER_TTL=${THROTTLER_TTL}
      - THROTTLER_LIMIT=${THROTTLER_LIMIT}
    ports:
      - 3001:3001
    networks:
      - backend

  redis:
    image: redis:7.0.8-alpine
    restart: always
    container_name: redis.cache
    ports:
      - 6379:6379
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:
